"""empty message

Revision ID: 5f67b53fb87a
Revises: 
Create Date: 2020-07-27 18:03:45.078532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f67b53fb87a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('app_lastname', sa.String(length=100), nullable=False),
    sa.Column('app_email', sa.String(length=100), nullable=False),
    sa.Column('app_phone', sa.String(length=12), nullable=False),
    sa.Column('app_time', sa.String(length=100), nullable=False),
    sa.Column('app_message', sa.String(length=500), nullable=False),
    sa.Column('app_status', sa.Boolean(), nullable=True),
    sa.Column('cont_createdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('bintro', sa.String(length=100), nullable=False),
    sa.Column('publictext', sa.String(length=100), nullable=False),
    sa.Column('privatext', sa.String(length=1000), nullable=False),
    sa.Column('blogimagen', sa.String(length=100), nullable=True),
    sa.Column('blogvideo', sa.String(length=100), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cont_name', sa.String(length=100), nullable=False),
    sa.Column('cont_lastname', sa.String(length=100), nullable=False),
    sa.Column('cont_email', sa.String(length=100), nullable=False),
    sa.Column('cont_phone', sa.String(length=12), nullable=False),
    sa.Column('cont_message', sa.String(length=500), nullable=False),
    sa.Column('cont_createdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rolename')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('contact')
    op.drop_table('blogs')
    op.drop_table('appointment')
    # ### end Alembic commands ###
